[project]
name = "mojiokoshiitai"
version = "0.1.0"
description = "リアルタイムで文字起こしをするプログラム"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.2.2",
    "pyaudio>=0.2.14",
    "speechrecognition>=3.14.1",
]
